CREATE TABLE users(
  id SERIAL PRIMARY KEY,
  email VARCHAR(255) NOT NULL UNIQUE,
  password VARCHAR(255) NOT NULL,
  name VARCHAR(255),
  surname VARCHAR(255)
);

CREATE TABLE tokens(
  token VARCHAR(255) NOT NULL UNIQUE,
  userId INTEGER,
  FOREIGN KEY (userId) REFERENCES users(id)
);