GET http://localhost:8080/api/users

###

GET http://localhost:8080/api/users/1

###

PATCH http://localhost:8080/api/users/1
Content-Type: application/json

{
  "name": "Konstantin",
  "surname": "Golubkov"
}

###

DELETE  http://localhost:8080/api/users/14

